# Base evaluation configuration
evaluation:
  # Evaluation settings
  max_length: 512
  num_beams: 4
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  repetition_penalty: 1.2
  
  # Metrics to compute
  metrics:
    - perplexity
    - accuracy
    - bleu
    - rouge
  
  # Output settings
  output:
    save_dir: ${paths.evaluation_dir}
    save_predictions: true
    save_metrics: true
    
  # Generation settings
  generation:
    max_new_tokens: 256
    do_sample: true
    num_return_sequences: 1
    
  # Batch settings
  batch:
    size: 8
    num_workers: 4
    pin_memory: true 