# Base model configuration
model:
  # Common model settings
  torch_dtype: float32
  device_map: auto
  trust_remote_code: false
  use_cache: false
  load_in_8bit: false
  load_in_4bit: false

  # Training settings specific to model
  training:
    per_device_train_batch_size: 4
    per_device_eval_batch_size: 4
    gradient_accumulation_steps: 4
    learning_rate: 5.0e-5
    max_length: 512 