defaults:
  - _self_

# Dataset Configuration
dataset:
  output_dir: ${env.DATASET_OUTPUT_DIR}  # Директория для сохранения датасета
  train_val_split_ratio: 0.8  # Соотношение train/validation

# Настройки CVE
cve:
  days_lookback: 365  # Количество дней для поиска CVE
  results_per_page: 100  # Результатов на страницу
  max_results: 10000  # Максимальное количество результатов
  min_cvss_score: 0.0  # Минимальный CVSS score

# Настройки MITRE ATT&CK
mitre_attack:
  include_tactics: true  # Включать ли тактики
  include_techniques: true  # Включать ли техники

# Настройки документации по безопасности
security_docs:
  include: true  # Включать ли документацию
  max_examples: 200  # Максимальное количество примеров 