defaults:
  - default

# Override settings for a full dataset
dataset:
  train_val_split_ratio: 0.8

cve:
  days_lookback: 365  # За последний год
  results_per_page: 100
  max_results: 10000  # Больше CVE
  min_cvss_score: 0.0  # Все уязвимости

mitre_attack:
  include_tactics: true
  include_techniques: true  # И тактики, и техники

security_docs:
  include: true
  max_examples: 200  # Больше примеров из документации 