# Base training configuration
training:
  # Training loop settings
  num_train_epochs: 3
  seed: 42
  max_grad_norm: 1.0
  lr_scheduler_type: cosine
  weight_decay: 0.01
  warmup_steps: 100

  # Optimization settings
  optimization:
    fp16: true
    gradient_checkpointing: true
    dataloader_num_workers: 4
    dataloader_pin_memory: true

  # Save settings
  save:
    save_strategy: steps
    save_steps: 100
    save_total_limit: 3 