# Main configuration file
defaults:
  - training/base
  - model: mistral  # Default model
  - peft: lora     # Default PEFT method
  - _self_

# Paths
paths:
  output_dir: ${oc.env:OUTPUT_DIR,models}
  logs: ${oc.env:LOGS_DIR,logs}
  cache_dir: ${oc.env:CACHE_DIR,.cache}

# Dataset settings
dataset:
  output_dir: ${oc.env:DATASET_OUTPUT_DIR,data/processed}
  train_val_split_ratio: 0.8
  cve:
    days_lookback: 365
    results_per_page: 100
    max_results: 10000
    min_cvss_score: 0.0
  mitre_attack:
    include_tactics: true
    include_techniques: true
  security_docs:
    include: true
    max_examples: 200

# Environment variables
env:
  NVD_API_KEY: ${oc.env:NVD_API_KEY}
  MITRE_ATTACK_URL: ${oc.env:MITRE_ATTACK_URL}
  DATASET_OUTPUT_DIR: ${oc.env:DATASET_OUTPUT_DIR,data/processed}
  TRAINING_OUTPUT_DIR: ${oc.env:TRAINING_OUTPUT_DIR,models/checkpoints}
  LOGS_DIR: ${oc.env:LOGS_DIR,logs}

# Hydra settings
hydra:
  run:
    dir: ${paths.output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${paths.output_dir}/sweeps/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

# Logging configuration
logging:
  wandb:
    enabled: false
    project: "security-llm"
    name: null  # Will be auto-generated if not set
  tensorboard:
    enabled: true
    log_dir: ${paths.logs}/tensorboard 