# Main configuration file
defaults:
  - model: mistral
  - peft: lora
  - training: base
  - _self_

# Main paths configuration
paths:
  # Base directories
  base_dir: ${oc.env:BASE_DIR,${oc.env:PWD}}
  models_dir: ${oc.env:MODELS_DIR,${paths.base_dir}/models}
  logs_dir: ${oc.env:LOGS_DIR,${paths.base_dir}/logs}
  
  # Model-specific paths
  checkpoints_dir: ${paths.models_dir}/checkpoints
  adapters_dir: ${paths.models_dir}/adapters
  tokenizer_dir: ${paths.models_dir}/tokenizer
  
  # Logging paths
  tensorboard_dir: ${paths.logs_dir}/tensorboard
  training_logs_dir: ${paths.logs_dir}/training
  
  # Cache directory
  cache_dir: ${oc.env:CACHE_DIR,${paths.base_dir}/.cache}

# Dataset settings
dataset:
  output_dir: ${oc.env:DATASET_OUTPUT_DIR,${paths.base_dir}/data/processed}
  train_val_split_ratio: 0.8
  cve:
    days_lookback: 365
    results_per_page: 100
    max_results: 10000
    min_cvss_score: 0.0
  mitre_attack:
    include_tactics: true
    include_techniques: true
  security_docs:
    include: true
    max_examples: 200

# Environment variables
env:
  NVD_API_KEY: ${oc.env:NVD_API_KEY}
  MITRE_ATTACK_URL: ${oc.env:MITRE_ATTACK_URL}
  BASE_DIR: ${oc.env:BASE_DIR,${oc.env:PWD}}
  MODELS_DIR: ${oc.env:MODELS_DIR,${paths.models_dir}}
  LOGS_DIR: ${oc.env:LOGS_DIR,${paths.logs_dir}}
  CACHE_DIR: ${oc.env:CACHE_DIR,${paths.cache_dir}}
  DATASET_OUTPUT_DIR: ${oc.env:DATASET_OUTPUT_DIR,${dataset.output_dir}}

# Hydra settings
hydra:
  run:
    dir: ${paths.training_logs_dir}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${paths.training_logs_dir}/sweeps/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

# Logging configuration
logging:
  wandb:
    enabled: false
    project: "security-llm"
    name: null  # Will be auto-generated if not set
  tensorboard:
    enabled: true
    log_dir: ${paths.tensorboard_dir} 